/* Copyright (c) 2021-2026 Richard Rodger, MIT License */

// Generated by ../embed-translate.js. Edit tabnas.plugin.json or alchemy/*,
// then run npm run embed.

type TranslationPart = Readonly<{
  entry: string
  source?: string
}>

type TranslationParts = Readonly<{
  manifest: string
  lift?: TranslationPart
  render?: TranslationPart
}>

const TRANSLATION: TranslationParts = Object.freeze({
  manifest: `{
  "$schema": "https://tabnas.dev/schema/plugin.schema.json",
  "name": "@tabnas/yaml",
  "go": "github.com/tabnas/yaml/go",
  "rust": "tabnas-yaml",
  "description": "YAML parsing for the tabnas engine.",
  "base": "@tabnas/jsonic",
  "engine": "@tabnas/parser",
  "grammar": "yaml-grammar.jsonic",
  "extensions": [
    ".yaml",
    ".yml"
  ],
  "mediaTypes": [
    "application/yaml"
  ],
  "languageId": "yaml",
  "pluginKind": "grammar",
  "grammarKind": "closure",
  "lexStream": "clean",
  "syncGroups": [
    "end",
    "comma",
    "close",
    "sync"
  ],
  "specDir": "test/spec",
  "clib": {
    "dir": "go/clib",
    "library": "libtabnasyaml",
    "abi": "v1",
    "errorCodes": [
      "usage",
      "grammar",
      "handle",
      "internal"
    ]
  },
  "errorCodes": [],
  "docs": "https://tabnas.dev/docs/packages",
  "repository": "https://github.com/tabnas/yaml",
  "versionSource": "ts/package.json",
  "translate": {
    "reads": "tree",
    "writes": "tree",
    "render": "alchemy/render.alc",
    "loss": [
      "Comments are not kept.",
      "Anchors and aliases are not kept: an alias is written as a copy of the value it names.",
      "Tags are not kept.",
      "Styles are not kept: every string and key is written double-quoted, and every collection in block style.",
      "A stream of several documents is written as one document, a sequence of them."
    ]
  }
}
`,
  render: Object.freeze({ entry: "yaml-render", source: `; YAML's render: a tree's events written as one YAML 1.2 document in
; block style. This is a library of definitions, each named \`yaml-...\`,
; which a host links with its own program (alchemy's \`compile_sources\`);
; its entry point is \`yaml-render\`, and nothing else here is the host's to
; call.
;
; The profile is always-quoted, as the CSV renderer's is: every string and
; every key is double-quoted (\`quoted\`: JSON's escapes, which YAML's
; double-quoted style reads, and the C1 controls its printable set
; excludes), so that no string reads back as a boolean, a null, a number
; or a nested mapping. A number is its lexeme, or as the JSON renderer
; writes it when it has none, and a non-finite one is \`.inf\`, \`-.inf\` or
; \`.nan\`. A mapping under a key, and a sequence under a key or inside a
; sequence, start on the next line, two spaces in; a sequence item is
; \`- \`, and a mapping in a sequence has its first key on the item's line.
; A container's opening is held until its first child or its end, so an
; empty one is \`{}\` or \`[]\` on its key's line. A key whose quoted form is
; longer than 1024 characters, past which YAML stops reading an implicit
; key, is written explicitly, \`? key\` on its own line.
;
; The events are a tree's: a mapping holds each key once. A walked value
; is one by construction; a host that streams a parse must refuse a
; member the parse repeats, since the render writes what it is given and
; YAML forbids a repeated key.
;
; The state is the stack of open containers, one marker each, so it grows
; with a document's nesting and never with its width: \`:object-open\` and
; \`:array-open\` for a container with nothing written yet, \`:object\` for a
; mapping waiting for a key, \`:member\` for one whose key is written and
; waits for the value, and \`:array\` for a sequence waiting for an item.
; Once the root value is written the state is \`[:root-done]\`, and nothing
; may follow it. Events no tree has fail with INPUT_INVALID, saying so.

def yaml-indent [s]
  repeat (count s) "  "

; The top marker, or \`:none\` before the root value.
def yaml-top [s]
  match (count s)
    case 0 :none
    case _ (top s)

; The top container under another marker.
def yaml-mark [marker s]
  push marker (pop s)

; A value completed: a mapping waiting for its member's value waits for
; its next key, and the root value, once written, is the document.
def yaml-done [s]
  match (count s)
    case 0 [:root-done]
    case _
      match (yaml-top s)
        case :member (yaml-mark :object s)
        case _ s

; What comes before a value whose parent is the top of s: a space on the
; key's line, or a dash, for a scalar or an empty container; a line break
; and the indentation for a mapping under a key; a line break for a
; sequence under a key; a dash and the first key for a mapping in a
; sequence; a dash alone for a sequence in a sequence.
def yaml-lead [shape s]
  match (count s)
    case 0 ""
    case _
      match (yaml-top s)
        case :member
          match shape
            case :mapping (concat "\\n" (yaml-indent s))
            case :sequence "\\n"
            case _ " "
        case :array
          match shape
            case :sequence (concat (yaml-indent (pop s)) "-\\n")
            case _ (concat (yaml-indent (pop s)) "- ")
        case _ (fail "the events hold a value where a key is due, which a tree's never do")

; A held sequence is opened by its first item.
def yaml-opened [s]
  match (count s)
    case 0 s
    case _
      match (yaml-top s)
        case :array-open (yaml-mark :array s)
        case _ s

def yaml-opening [s]
  match (count s)
    case 0 ""
    case _
      match (yaml-top s)
        case :array-open (yaml-lead :sequence (pop s))
        case _ ""

def yaml-number [n]
  match (number-class n)
    case :finite (scalar-text csv-options n)
    case :infinity ".inf"
    case :negative-infinity "-.inf"
    case :nan ".nan"

def yaml-scalar [value]
  match (kind value)
    case :null "null"
    case :boolean
      match value
        case true "true"
        case false "false"
    case :number (yaml-number value)
    case _ (quoted value)

; A key at the column \`at\`: implicit while its quoted form is at most
; 1024 characters, past which YAML stops reading an implicit key, and
; explicit beyond, \`? key\` on its own line and the value after a \`:\` at
; the key's column.
def yaml-key [name at]
  match (compare (length (quoted name)) 1024)
    case :greater (concat "? " (quoted name) "\\n" at ":")
    case _ (concat (quoted name) ":")

; A key, written where the mapping's keys go.
def yaml-member [name s]
  match (yaml-top s)
    case :object-open
      transition (yaml-mark :member s) [(yaml-lead :mapping (pop s)) (yaml-key name (yaml-indent (pop s)))]
    case :object
      transition (yaml-mark :member s) [(yaml-indent (pop s)) (yaml-key name (yaml-indent (pop s)))]
    case _ (fail "the events hold a key where a value is due, which a tree's never do")

; The state a value may begin in: anywhere but a mapping waiting for a key.
def yaml-value [s]
  match (yaml-top s)
    case :object-open (fail "the events hold a value where a key is due, which a tree's never do")
    case :object (fail "the events hold a value where a key is due, which a tree's never do")
    case _ s

def yaml-step [s event]
  match (yaml-top s)
    case :root-done (fail "the events hold more after the root value, which a tree's never do")
    case _ (yaml-event s event)

def yaml-event [s event]
  match event
    case object-start
      transition (push :object-open (yaml-opened (yaml-value s))) [(yaml-opening s)]
    case array-start
      transition (push :array-open (yaml-opened (yaml-value s))) [(yaml-opening s)]
    case (key name) (yaml-member name s)
    case (scalar value)
      let [s2 (yaml-opened (yaml-value s))]
        transition (yaml-done s2) [(yaml-opening s) (yaml-lead :scalar s2) (yaml-scalar value) "\\n"]
    case object-end
      match (yaml-top s)
        case :object-open
          transition (yaml-done (pop s)) [(yaml-lead :scalar (pop s)) "{}\\n"]
        case :object
          transition (yaml-done (pop s)) []
        case :member
          fail "the events end a mapping after a key and before its value, which a tree's never do"
        case _
          fail "the events end a mapping that is not open, which a tree's never do"
    case array-end
      match (yaml-top s)
        case :array-open
          transition (yaml-done (pop s)) [(yaml-lead :scalar (pop s)) "[]\\n"]
        case :array
          transition (yaml-done (pop s)) []
        case _
          fail "the events end a sequence that is not open, which a tree's never do"

def yaml-finish [s]
  match (yaml-top s)
    case :root-done []
    case :none (fail "the events hold no value, where a tree's hold one")
    case _ (fail "the events ended inside a container")

; The render: the tree's events in, the document's text out.
def yaml-render [input]
  join ""
    scan-emit [] yaml-step yaml-finish (events input)
` })
})

function translate (): TranslationParts | undefined {
  return TRANSLATION
}

export {
  translate,
}

export type {
  TranslationPart,
  TranslationParts,
}
